/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as TraceNfcIdRouteImport } from './routes/trace.$nfcId'
import { Route as AppVisionRouteImport } from './routes/_app.vision'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppInspectionsRouteImport } from './routes/_app.inspections'
import { Route as AppGatewaysRouteImport } from './routes/_app.gateways'
import { Route as AppExpertisesRouteImport } from './routes/_app.expertises'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppArtworksNewRouteImport } from './routes/_app.artworks.new'
import { Route as AppArtworksIdRouteImport } from './routes/_app.artworks.$id'
import { Route as ApiPublicSensorsIngestRouteImport } from './routes/api/public/sensors/ingest'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TraceNfcIdRoute = TraceNfcIdRouteImport.update({
  id: '/trace/$nfcId',
  path: '/trace/$nfcId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisionRoute = AppVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppGatewaysRoute = AppGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertisesRoute = AppExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppArtworksNewRoute = AppArtworksNewRouteImport.update({
  id: '/artworks/new',
  path: '/artworks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppArtworksIdRoute = AppArtworksIdRouteImport.update({
  id: '/artworks/$id',
  path: '/artworks/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSensorsIngestRoute = ApiPublicSensorsIngestRouteImport.update({
  id: '/api/public/sensors/ingest',
  path: '/api/public/sensors/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/chat': typeof AppChatRoute
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/expertises': typeof AppExpertisesRoute
  '/gateways': typeof AppGatewaysRoute
  '/inspections': typeof AppInspectionsRoute
  '/scan': typeof AppScanRoute
  '/vision': typeof AppVisionRoute
  '/trace/$nfcId': typeof TraceNfcIdRoute
  '/artworks/$id': typeof AppArtworksIdRoute
  '/artworks/new': typeof AppArtworksNewRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/chat': typeof AppChatRoute
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/expertises': typeof AppExpertisesRoute
  '/gateways': typeof AppGatewaysRoute
  '/inspections': typeof AppInspectionsRoute
  '/scan': typeof AppScanRoute
  '/vision': typeof AppVisionRoute
  '/trace/$nfcId': typeof TraceNfcIdRoute
  '/': typeof AppIndexRoute
  '/artworks/$id': typeof AppArtworksIdRoute
  '/artworks/new': typeof AppArtworksNewRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expertises': typeof AppExpertisesRoute
  '/_app/gateways': typeof AppGatewaysRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/vision': typeof AppVisionRoute
  '/trace/$nfcId': typeof TraceNfcIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/artworks/$id': typeof AppArtworksIdRoute
  '/_app/artworks/new': typeof AppArtworksNewRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/alerts'
    | '/chat'
    | '/compliance'
    | '/dashboard'
    | '/expertises'
    | '/gateways'
    | '/inspections'
    | '/scan'
    | '/vision'
    | '/trace/$nfcId'
    | '/artworks/$id'
    | '/artworks/new'
    | '/api/public/sensors/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/alerts'
    | '/chat'
    | '/compliance'
    | '/dashboard'
    | '/expertises'
    | '/gateways'
    | '/inspections'
    | '/scan'
    | '/vision'
    | '/trace/$nfcId'
    | '/'
    | '/artworks/$id'
    | '/artworks/new'
    | '/api/public/sensors/ingest'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/chat'
    | '/_app/compliance'
    | '/_app/dashboard'
    | '/_app/expertises'
    | '/_app/gateways'
    | '/_app/inspections'
    | '/_app/scan'
    | '/_app/vision'
    | '/trace/$nfcId'
    | '/_app/'
    | '/_app/artworks/$id'
    | '/_app/artworks/new'
    | '/api/public/sensors/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TraceNfcIdRoute: typeof TraceNfcIdRoute
  ApiPublicSensorsIngestRoute: typeof ApiPublicSensorsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/trace/$nfcId': {
      id: '/trace/$nfcId'
      path: '/trace/$nfcId'
      fullPath: '/trace/$nfcId'
      preLoaderRoute: typeof TraceNfcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vision': {
      id: '/_app/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof AppVisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gateways': {
      id: '/_app/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof AppGatewaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expertises': {
      id: '/_app/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof AppExpertisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artworks/new': {
      id: '/_app/artworks/new'
      path: '/artworks/new'
      fullPath: '/artworks/new'
      preLoaderRoute: typeof AppArtworksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artworks/$id': {
      id: '/_app/artworks/$id'
      path: '/artworks/$id'
      fullPath: '/artworks/$id'
      preLoaderRoute: typeof AppArtworksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sensors/ingest': {
      id: '/api/public/sensors/ingest'
      path: '/api/public/sensors/ingest'
      fullPath: '/api/public/sensors/ingest'
      preLoaderRoute: typeof ApiPublicSensorsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppChatRoute: typeof AppChatRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpertisesRoute: typeof AppExpertisesRoute
  AppGatewaysRoute: typeof AppGatewaysRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppScanRoute: typeof AppScanRoute
  AppVisionRoute: typeof AppVisionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArtworksIdRoute: typeof AppArtworksIdRoute
  AppArtworksNewRoute: typeof AppArtworksNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppChatRoute: AppChatRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpertisesRoute: AppExpertisesRoute,
  AppGatewaysRoute: AppGatewaysRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppScanRoute: AppScanRoute,
  AppVisionRoute: AppVisionRoute,
  AppIndexRoute: AppIndexRoute,
  AppArtworksIdRoute: AppArtworksIdRoute,
  AppArtworksNewRoute: AppArtworksNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TraceNfcIdRoute: TraceNfcIdRoute,
  ApiPublicSensorsIngestRoute: ApiPublicSensorsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
